#!/bin/sh

NEO4J_HOME=/var/lib/neo4j

ulimit -n 65536
echo 'dbms.security.auth_enabled=false' >> $NEO4J_HOME/conf/neo4j-server.properties
sed -i "s|#org.neo4j.server.webserver.address=0.0.0.0|org.neo4j.server.webserver.address=$HOSTNAME|g" $NEO4J_HOME/conf/neo4j-server.properties
$NEO4J_HOME/bin/neo4j console
